[package]
name = "binp"
version = "1.0.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
clap = { version = "4.5.8", features = ["derive"] }
crossterm = "0.27.0"
notify = "6.1.1"
serde = { version = "1.0.203", features = ["derive"] }
serde_yaml = "0.9.34"
tabled = "0.15.0"
